version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: yummio-postgres
    environment:
      POSTGRES_DB: yummio_db
      POSTGRES_USER: yummio
      POSTGRES_PASSWORD: yummio_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yummio-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: yummio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yummio-network

  # Yummio API
  api:
    build: .
    container_name: yummio-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=yummio
      - DB_PASSWORD=yummio_password
      - DB_NAME=yummio_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GIN_MODE=release
    depends_on:
      - postgres
      - redis
    networks:
      - yummio-network
    volumes:
      - ./.env:/root/.env

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: yummio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - yummio-network

volumes:
  postgres_data:
  redis_data:

networks:
  yummio-network:
    driver: bridge